### ISSUE TITLE
Build Representer and Analyzer

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/haxe#133]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

## Representer

In Exercism v3, we're introducing a new (optional) tool: the [representer](https://github.com/exercism/v3-docs/tree/main/anatomy/track-tooling/representers). The goal of the representer is to take a solution and returning a representation, which is an extraction of a solution to its essence with normalized names, comments, spacing, etc. but still uniquely identifying the approach taken. Two different ways of solving the same exercise must not have the same representation.

Each representer is track-specific. When a new solution is submitted, we run the track's representer, which outputs two JSON files that describe the representation.

Once we have a normalized representation for a solution, a team of vetted mentors will look at the solution and comment on it (if needed). These comments will then automatically be submitted to each new solution with the same representation. A notification will be sent for old solutions with a matching representation.

Each track should build a representer according to [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/representers/interface.md). For tracks building a representer from scratch, we have a [starting guide](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/representers/creating-from-scratch.md).

The representer is an optional tool though, which means that if a track does not have a representer, it will still function normally.

## Analyzer

In Exercism v3, we are making increased use of our v2 [analyzers](https://github.com/exercism/v3-docs/tree/main/anatomy/track-tooling/analyzers). Analyzers automatically assess student's submissions and provide mentor-style commentary. They can be used to catch common mistakes and/or do complex solution analysis that can't easily be done directly in a test suite.

Each analyzer is track-specific. When a new solution is submitted, we run the track's analyzer, which outputs a JSON file that contains the analysis results.

In v2, analyzer comments were given to a mentor to pass to a student. In v3, the analyzers will normally output directly to students, although we have added an extra key to output suggestions to mentors. If your track already has an analyzer, the only requisite change is updating the outputted copy to be student-facing.

Each track should build an analyzer according to [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/analyzers/interface.md). For tracks building an analyzer from scratch, we have a [starting guide](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/analyzers/creating-from-scratch.md).

The analyzer is an optional tool though, which means that if a track does not have an analyzer, it will still function normally.

## Goal 1

Build a representer for your track according to [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/representers/interface.md). Check [this page](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/representers/creating-from-scratch.md) to help you get started with building a representer.

Note that the simplest representer is one that merely returns the solution's source code.

It can be very useful to check how [other tracks have implemented their representer](https://github.com/search?q=org%3Aexercism+representer&type=repositories).

## Goal 2

Build an analyzer for your track according to [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/analyzers/interface.md). Check [this page](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/analyzers/creating-from-scratch.md) to help you get started with building an analyzer.

It can be very useful to check how [other tracks have implemented their analyzer](https://github.com/search?q=org%3Aexercism+analyzer&type=repositories).

## Choosing between representer and analyzer

If you want to build both, we recommend starting by building the representer for the following reasons:

- Representers are usually (far) easier to implement
- Representers can have a far bigger impact on the mentoring load than analyzers by empowering mentors
- Representers apply to _all_ exercises, whereas analyzers usually target specific exercises or a subset

## Tracking

https://github.com/exercism/v3-launch/issues/8

**Comment by davidbruce** [comment]
I don't believe a Representer is necessary at the moment.  Due to the Haxe track being young and without a pool of solutions it would be tough to create this kind of automated feedback without a dataset.  

As for the analyzer, I have requested a repo to be created for Haxe https://github.com/exercism/exercism/issues/5466. 
It shouldn't be too hard to get something basic setup utilizing [haxe-checkstyle](https://github.com/HaxeCheckstyle/haxe-checkstyle).   There are many styles that are adopted in the Haxe community that are pretty consistent without there being a primary spec.  

Type declarations, `:`, appear to be where the most inconsistency lies.  In the standard library and popular library OpenFL you will find no space around the colon e.g. `var x:Type` and `function name(x:Type):Type`.  I believe this is mostly an artifact of Haxe's history with Actionscript which followed the same pattern. 

Another example is Heaps, arguably the most successful game engine in Haxe due to recognition of games, such as Dead Cells, Northgard, and Evoland.  It follows Ocaml's style for explicit typing of having space on both sides of the colon e.g. `var x : Type` and `function name(x : Type) : Type`. If you look at any code by Nicolas Cannasse, the creator of Haxe, this appears to be his preferred style. 

Strangely enough, I think following a standard of a single space after the colon would be the best route e.g. `var x: Type` and `function name(x: Type): Type`. I think this is appropriate because it follows the official style guides of Typescript, Python, Rust, Nim, Zig and PHP(at least for function return types).  Since there is no official guide, following what appears to be a very common pattern among other languages, it may lead to the least amount of friction for new users. 

If an official stance on type declarations occurs we can always change it in the future.  I will probably write up a style guide and the decisions for items as a part of the analyzer implementation.  If necessary I'll reach out to the Haxe Foundation for input.

**Comment by mfoda** [comment]
Interesting points David. One thing I wanted to add as someone relatively new to haxe is that the most beginner-friendly standard for type declarations to me seems to be the default used by the vshaxe plugin [formatter](https://github.com/vshaxe/vshaxe/wiki/Formatting) (which is no spaces around the colon). Deviating from its defaults would require users to create a `hxformat.json` which is more friction imo.

**Comment by davidbruce** [comment]
I forgot about that plugin, so you bring up a good point. I think with exercise v3's online editor we wont have to worry too much about it.  
I'll give it some more thought.

**Comment by ErikSchierboom** [comment]
> I don't believe a Representer is necessary at the moment. Due to the Haxe track being young and without a pool of solutions it would be tough to create this kind of automated feedback without a dataset.

Just to add to this a little bit. I'd argue that building an analyzer without a pool of solutions is harder than building a representer without those solutions. That said, the fact that there are relatively little solutions _is_ a good argument for the representer being of less use than a busy track. That said, a basic representer can usually be implemented quite easily. You mentioned a formatter in your above comment. A simple representer which just applies formatting could still be a useful formatter.

Just wanted to give you my thoughts :)

**Comment by mfoda** [comment]
I'll start working on the Representer. If anyone else is already working on that please let me know.

**Comment by ErikSchierboom** [comment]
We're closing this issue as two separate issues have been created to replace this combined issue.
